### ISSUE TITLE
cannot convert from 'Aguacongas.IdentityServer.Store.IAdminStore<Aguacongas.IdentityServer.Store.Entity.Culture>' to 'Aguacongas.TheIdServer.BlazorApp.Services.IReadOnlyCultureStore'

### ISSUE THREAD

**Issue by brianpowers27** [Aguafrommars/Templates#17]
On following instructions for setting up from template, I receive the following error on build.  
Severity	Code	Description	Project	Path	File	Line	Suppression State
Error	CS1503	Argument 2: cannot convert from 'Aguacongas.IdentityServer.Store.IAdminStore<Aguacongas.IdentityServer.Store.Entity.Culture>' to 'Aguacongas.TheIdServer.BlazorApp.Services.IReadOnlyCultureStore'	TheIdServer	C:\dev\theidserverbp\TheIdServer\src\TheIdServer\Services	C:\dev\theidserverbp\TheIdServer\src\TheIdServer\Services\PreRenderStringLocalizer.cs	13	Active

I believe that pulling in the following change from the parent project would resolve thie issue.  https://github.com/Aguafrommars/TheIdServer/issues/331

**Comment by aguacongas** [comment]
@brianpowers27 thanks to contribute. 
fixed in [1.0.2](https://github.com/Aguafrommars/Templates/releases/tag/1.0.2)
