### ISSUE TITLE
New Template version

### ISSUE THREAD

**Issue by grantvine-sc** [Aguafrommars/Templates#197]
Hi There,

I notice there are updates to this repository, but in terms of releases on NuGet there is still only a 4.0.0 release which (when used) doesnt seem to work correctly:

<img width="1309" alt="image" src="https://user-images.githubusercontent.com/121936135/223118331-09afac14-46fc-4e38-b43f-8e51f7548a1e.png">

Please could you advise as I have updated libraries, but it appears the bugs being found are in the supporting use of the framework and I am not quite sure where to look first ?

Thanks

**Comment by aguacongas** [comment]
Hi, thx to contribute.  
To work around this, just add a package reference `Microsoft.Extensions.FileProviders.Embedded` in your Compare3.csproj (`dotnet add package Microsoft.Extensions.FileProviders.Embedded`).  
I'm going to a fix it.
