### ISSUE TITLE
Is this Template still active?

### ISSUE THREAD

**Issue by lecramr** [Aguafrommars/Templates#280]
Hey, 

is this template still active maintained? It looks like it currently creates a .Net 7 Solution, which for me at least is broken, are there any plans to support .Net 8 with this template?

Thanks in advance!

**Comment by aguacongas** [comment]
Yes, but not yet ready

**Comment by aguacongas** [comment]
Upgrade the template to [5.0.0](https://github.com/Aguafrommars/Templates/releases/tag/5.0.0)

**Comment by lecramr** [comment]
Thank you very much! :)
