### ISSUE TITLE
@aguacongas My project upgrade to 5.0.2 but the ```Exception2``` still happened.

### ISSUE THREAD

**Issue by EversongWoods** [Aguafrommars/Templates#322]
@aguacongas My project upgrade to 5.0.1 but the ```Exception2``` still happened.
![屏幕截图 2024-09-15 115020](https://github.com/user-attachments/assets/cb606adf-6f5e-43a7-8569-58068a316ef1)
![屏幕截图 2024-09-15 115048](https://github.com/user-attachments/assets/5b0193a1-9dc1-48c2-aaee-73b7882ff7a1)

_Originally posted by @EversongWoods in https://github.com/Aguafrommars/Templates/issues/315#issuecomment-2351344435_

**Comment by aguacongas** [comment]
Ok, there was a missing call to *UseIdentityServerAdminAuthentication* in *ApplicationBuilderExtensions*. Copy the code from [ApplicationBuilderExtensions](https://github.com/Aguafrommars/Templates/blob/master/TheIdServer.Duende/src/TIS/Extensions/ApplicationBuilderExtensions.cs) by keeping your namespace should fix it.
